# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBx80HpyErz5g0XXyHmQFr0tWwLDQU9c
"""

if __name__ == "__main__":
   # running the app
    app.run()